### ISSUE TITLE
Access Control for Normal Users

### ISSUE THREAD

**Issue by stardust66** [StPauls-Computer-Science/tucktogo-backend#6]
Standard users should only be able to do the following:
- Order for themselves
- Check on orders they ordered

**Comment by RyanRio** [comment]
This can pretty easily be done using policies.js, no?

**Comment by stardust66** [comment]
I think it's different because `policies.js` can't check for details of the order. We can either write some specialized policies or have some access control inside the controllers.

**Comment by stardust66** [comment]
Solved by [`isAdmin.js`](https://github.com/StPauls-Computer-Science/tucktogo-backend/blob/master/api/policies/isAdmin.js) policy.
